### ISSUE TITLE
where is the all.lm

### ISSUE THREAD

**Issue by jind11** [parajain/uctf#1]
Hi, I am wondering where to download the all.lm for the kenLM. Thanks!

**Comment by parajain** [comment]
Hi, I guess that was not checked in due to large size. 

I understand that should have at least documented it in detail with the exact process to train, but I missed it. Sorry about that.

Please refer: https://github.com/kpu/kenlm

Thanks

**Comment by jind11** [comment]
Thanks for the quick response! I have checked the kenlm github page but still cannot the exact link to download the "all.lm" you used. Could you help with it?

**Comment by parajain** [comment]
Hi,

Yes, that is not there. The kenlm git has the code to train a language model, which was names as all.lm. I do not have a trained language model with me to share now. However, kenlm page gives detailed instruction on how you can train one. 

I hope this helps.

**Comment by parajain** [comment]
https://github.com/parajain/uctf/issues/3
